include ./theme.conf

font_family Fira Code

map ctrl+shift+p nth_window -1

hide_window_decorations False
wayland_titlebar_color background

font_size 11.0
# Override zoom controls so increments are smoother
map ctrl+shift+kp_add change_font_size all +0.5
map ctrl+shift+kp_substract change_font_size all -0.5
map ctrl+shift+backspace change_font_size all 0

# Remove confirmation dialog when closing
confirm_os_window_close 0

shell zellij -l welcome
#shell zellij 
