[language-server.rust-analyzer.config.check]
command = "clippy"

# [language-server.basedpyright.config.basedpyright.analysis]
# typeCheckingMode = "basic"

[[language]]
name = "c"
language-servers = ["clangd", "typos", "harper-ls-code"]

[[language]]
name = "cpp"
language-servers = ["clangd", "typos", "harper-ls-code"]

[[language]]
name = "rust"
auto-format = true
language-servers = ["rust-analyzer", "typos", "harper-ls-code"]

[[language]]
name = "python"
language-servers = ["ty", "ruff", "typos", "harper-ls-code"]
auto-format = false

[[language]]
name = "markdown"
language-servers = ["marksman", "harper-ls"]

[[language]]
name = "toml"
formatter = { command = "taplo", args = ["fmt", "-"] }
language-servers = ["taplo", "harper-ls"]

[language-server.harper-ls.config.harper-ls]
dialect = "British"

# A specific Harper config for code analyses
[language-server.harper-ls-code]
command = "harper-ls"
args = ["--stdio"]
[language-server.harper-ls-code.config.harper-ls]
dialect = "British"
[language-server.harper-ls-code.config.harper-ls.linters]
ExpandParameter = false
MassNouns = false
# Harper spellcheck is not excellent with code comments. We use typos instead
SpellCheck = false
SentenceCapitalization = false
ToDoHyphen = false

[language-server.typos]
command = "typos-lsp"
config.diagnosticSeverity = "Hint"
